---
- name: Crear redes y subredes en Openstack
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Crear red DMZ
      openstack.cloud.network:
        cloud: devstack
        state: present
        name: red_dmz

    - name: Crear subred DMZ
      openstack.cloud.subnet:
        cloud: devstack
        state: present
        name: subred_dmz
        network_name: red_dmz
        cidr: 10.0.10.0/24
        gateway_ip: 10.0.10.1
        enable_dhcp: false

    - name: Crear red LAN
      openstack.cloud.network:
        cloud: devstack
        state: present
        name: red_LAN

    - name: Crear subred LAN
      openstack.cloud.subnet:
        cloud: devstack
        state: present
        name: subred_LAN
        network_name: red_LAN
        cidr: 172.21.1.0/24
        gateway_ip: 172.21.1.1
        enable_dhcp: true
