---
- name: Lanzar instancia con metadatos personalizados
  hosts: localhost
  tasks:
    - name: Lanzar instancia con metadata
      os_server:
        cloud: devstack
        state: present
        name: mi_instancia_ansible
        image: Ubuntu-20.04
        flavor: m1.small
        key_name: clave_admin
        network: red_lan
        meta:
          proyecto: UNIR
          autor: LMG
          uso: pruebas_tfg
